// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxHaKHs7x009CBnSZ3WOEAoBk0Cye6Yjc',
    appId: '1:640966374911:web:a5e57c4589e81ac3f9e3ca',
    messagingSenderId: '640966374911',
    projectId: 'project-d77ee',
    authDomain: 'project-d77ee.firebaseapp.com',
    storageBucket: 'project-d77ee.firebasestorage.app',
    measurementId: 'G-VGWR89EK8N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn83r4hwwe_5ArSNH7FJDaFZ2TJ__h9fM',
    appId: '1:640966374911:android:27a4a1a19780f285f9e3ca',
    messagingSenderId: '640966374911',
    projectId: 'project-d77ee',
    storageBucket: 'project-d77ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_DR2cAN8LanMwxL8aW2Rd_n0VKAfSEFo',
    appId: '1:640966374911:ios:4f617f19442d6b4bf9e3ca',
    messagingSenderId: '640966374911',
    projectId: 'project-d77ee',
    storageBucket: 'project-d77ee.firebasestorage.app',
    androidClientId: '640966374911-8ighs5jedlsnf3dnv2g2lo5imkosaudk.apps.googleusercontent.com',
    iosClientId: '640966374911-tpvje85keml70u6shoejgrhch7mg0c4u.apps.googleusercontent.com',
    iosBundleId: 'com.example.domVmeste',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_DR2cAN8LanMwxL8aW2Rd_n0VKAfSEFo',
    appId: '1:640966374911:ios:4f617f19442d6b4bf9e3ca',
    messagingSenderId: '640966374911',
    projectId: 'project-d77ee',
    storageBucket: 'project-d77ee.firebasestorage.app',
    androidClientId: '640966374911-8ighs5jedlsnf3dnv2g2lo5imkosaudk.apps.googleusercontent.com',
    iosClientId: '640966374911-tpvje85keml70u6shoejgrhch7mg0c4u.apps.googleusercontent.com',
    iosBundleId: 'com.example.domVmeste',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxHaKHs7x009CBnSZ3WOEAoBk0Cye6Yjc',
    appId: '1:640966374911:web:179b4dde2a7e7b57f9e3ca',
    messagingSenderId: '640966374911',
    projectId: 'project-d77ee',
    authDomain: 'project-d77ee.firebaseapp.com',
    storageBucket: 'project-d77ee.firebasestorage.app',
    measurementId: 'G-EW6NDTF50T',
  );
}
